S03 us122 table viewed completement implémentée
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #125
Opened 2023-06-27 17:35 UTC by l00ma

ajout de:
-Suppression d'un user par son id
-Suppression d'une video par son id

2023-06-27 18:19 UTC, maxdlr reviewed
En attente de la réponse de @aldaitzwild à mon commentaire.

2023-06-27 18:19 UTC, maxdlr commented on src/Controller/DeleteController.php
> +<?php
Ça ressemble beaucoup à un service à importer dans les controllers déjà existants de vidéo et user, nan ?

@aldaitzwild j'ai tort ?

2023-06-27 21:32 UTC, l00ma commented on src/Controller/DeleteController.php
> +<?php
J'ai passé le code en service. 
Par contre les appels restent dans le delete controller
J'ai tort ou bien? :)

2023-06-27 22:13 UTC, maxdlr commented on src/Controller/DeleteController.php
> +<?php
Bah comme tu balances tout dans les routes /vidéo et /user je les aurais mis avec leur controllers quoi
Ça fait un controller en moins à gérer

💻🔫

2023-06-28 06:43 UTC, val-fr69 approved these changes

2023-07-03 09:37 UTC, maxdlr approved these changes

2023-07-03 10:05 UTC, aldaitzwild requested changes

2023-07-03 10:05 UTC, aldaitzwild commented on src/Controller/Admin/TagCrudController.php
> +use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
Useless "use"

2023-07-03 13:58 UTC, aldaitzwild approved these changes

2023-07-03 13:58 UTC, merged