add search by title name in modal input
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #127
Opened 2023-07-02 13:42 UTC by maxdlr

2023-07-03 12:22 UTC, val-fr69 approved these changes

2023-07-03 12:45 UTC, l00ma approved these changes

2023-07-03 14:02 UTC, aldaitzwild requested changes

2023-07-03 14:02 UTC, aldaitzwild commented on assets/searchVideos.js
> +})
No ! You should document.createElement() to add this part

2023-07-05 08:48 UTC, aldaitzwild requested changes

2023-07-05 08:48 UTC, aldaitzwild commented on assets/searchVideos.js
> +                    let searchResult = html.body;
I don't understand why you do this ? You shouldn't have a `<body>` in your response

2023-07-05 14:34 UTC, aldaitzwild approved these changes

2023-07-05 14:34 UTC, merged

2023-07-05 14:35 UTC, l00ma approved these changes