S04 feat user comments fred
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #129
Opened 2023-07-03 19:06 UTC by l00ma

2023-07-04 08:27 UTC, val-fr69 approved these changes

2023-07-04 10:25 UTC, aldaitzwild requested changes

2023-07-04 10:25 UTC, aldaitzwild commented on assets/comment.js
> +postBlock.classList.add('align-items-end');
Why don't you put those classes directly in the twig ?

2023-07-04 10:25 UTC, aldaitzwild commented on assets/comment.js
> +                divToAppend.insertAdjacentHTML('afterbegin', CommentHtml);
Well ... that's awful. Try a similar implementation as Max to not handle your HTML in you JS

2023-07-05 08:52 UTC, aldaitzwild approved these changes

2023-07-05 08:52 UTC, merged