S04 issue99/105 header admin
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #134
Opened 2023-07-05 14:49 UTC by val-fr69

Implementation of header customization from the admin part + new css adapted to the latest feature implemented

2023-07-05 14:51 UTC, maxdlr approved these changes

2023-07-05 20:10 UTC, l00ma approved these changes

2023-07-06 07:44 UTC, maxdlr requested changes

2023-07-06 07:44 UTC, maxdlr commented on templates/home/index.html.twig
> +<<<<<<< HEAD
A supprimer

2023-07-06 07:44 UTC, maxdlr commented on templates/home/index.html.twig
> +=======
Pareil

2023-07-06 07:44 UTC, maxdlr commented on templates/home/index.html.twig
> +>>>>>>> c3ec14ee8c46161ac1b9832dbe85840422b0e27c
Pareil

2023-07-06 07:47 UTC, aldaitzwild requested changes

2023-07-06 07:47 UTC, aldaitzwild commented on templates/home/index.html.twig
> +<<<<<<< HEAD
Unresolved conflict

2023-07-06 07:49 UTC, maxdlr approved these changes

2023-07-06 07:49 UTC, l00ma approved these changes

2023-07-06 07:50 UTC, merged