Fix bug
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #178
Opened 2023-07-12 14:05 UTC by val-fr69

fix bug css

2023-07-12 14:23 UTC, maxdlr approved these changes

2023-07-12 14:25 UTC, l00ma approved these changes

2023-07-12 15:13 UTC, aldaitzwild requested changes

2023-07-12 15:13 UTC, aldaitzwild commented on templates/user/index.html.twig
> +>>>>>>> 6fe747610ae77f42c6860183b7c0a47a9de6e3bd
Unresolved conflict

2023-07-13 07:31 UTC, aldaitzwild requested changes

2023-07-13 07:31 UTC, aldaitzwild commented on assets/videos/64aebcd92fb70.mp4
Why is there this video ? It doesn't used by the fixtures. If it's just a test withdraw it

2023-07-13 07:52 UTC, aldaitzwild approved these changes

2023-07-13 08:04 UTC, merged