S06 issue192 contact page
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #195
Opened 2023-07-13 14:17 UTC by maxdlr

- add contact: controller, type, entity, repository, template and style
- add flash upon successfully sent
- add admin interface to manage message
- removed useless admin constrain

2023-07-13 14:36 UTC, val-fr69 approved these changes

2023-07-13 14:46 UTC, l00ma commented on src/Controller/ContactController.php
> +    #[Route('', name: 'index')]
la ligne 16 ne sert a rien, enleve-la et change ton code dessous comme suit :

```
class ContactController extends AbstractController
{
    #[Route('/contact', name: 'contact_index')]
```

2023-07-13 14:57 UTC, l00ma approved these changes

2023-07-16 22:44 UTC, maxdlr commented on templates/base.html.twig
> +</html></html>
?

2023-07-17 06:58 UTC, aldaitzwild requested changes

2023-07-17 06:58 UTC, aldaitzwild commented on templates/base.html.twig
> +</html></html>
Yes that's a problem...

2023-07-17 07:41 UTC, aldaitzwild approved these changes

2023-07-17 07:42 UTC, merged