S06 issue194 add galleries
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #196
Opened 2023-07-14 10:10 UTC by maxdlr

- add small thumbnails galleries to homepage & update trendigTags
- removed gifs & add premium badge & gifs to small thumbnails
- add bottom margin

2023-07-14 13:05 UTC, l00ma approved these changes

2023-07-16 22:39 UTC, maxdlr commented on src/Twig/Components/SmallVideoGalleryComponent.php
> +    public ?int $videoPlayedId = null;
Unused

2023-07-16 22:39 UTC, maxdlr commented on src/Twig/Components/SmallVideoGalleryComponent.php
> +    public int $count;
Unused

2023-07-17 06:59 UTC, aldaitzwild requested changes

2023-07-17 06:59 UTC, aldaitzwild commented on src/Twig/Components/SmallVideoGalleryComponent.php
> +    public ?int $videoPlayedId = null;
also good point

2023-07-17 07:44 UTC, aldaitzwild approved these changes

2023-07-17 07:44 UTC, merged