S06 issue 190 redirect in admin dashboard
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #198
Opened 2023-07-14 19:00 UTC by l00ma

2023-07-15 09:10 UTC, maxdlr commented on src/Controller/DeleteController.php
> +            $url .= '?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CUserCrudController';
Tu es sur que ces liens seront toujours les mêmes ? Aucun moyen d'en faire une route nommée ?

2023-07-15 09:10 UTC, maxdlr commented on src/Controller/DeleteController.php
> +            $url .= '?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CVideoCrudController';
Idem

2023-07-15 09:48 UTC, l00ma commented on src/Controller/DeleteController.php
> +            $url .= '?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CUserCrudController';
non pas moyen, mais j'ai corrigé pour faire un truc plus propre:
je remplace ceci
 $url .= '?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CUserCrudController';
par cela
 $url = $urlGenerator->generate('admin_dashboard', [
                'crudAction' => 'index',
                'crudControllerFqcn' => 'App\Controller\Admin\UserCrudController',
            ]);

2023-07-15 09:49 UTC, l00ma commented on src/Controller/DeleteController.php
> +            $url .= '?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CVideoCrudController';
idem, j'ai corrigé

2023-07-15 10:18 UTC, maxdlr commented on src/Controller/DeleteController.php
> +            $url .= '?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CUserCrudController';
Ah bah nickel !

2023-07-15 10:20 UTC, maxdlr approved these changes

2023-07-17 07:01 UTC, aldaitzwild requested changes

2023-07-17 07:01 UTC, aldaitzwild commented on src/Controller/DeleteController.php
> +                'crudControllerFqcn' => 'App\Controller\Admin\UserCrudController',
use UserCrudController::class syntax

2023-07-17 08:14 UTC, maxdlr approved these changes

2023-07-17 12:50 UTC, merged