S03US62 add users dashboard
WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital pull request #87
Opened 2023-06-21 15:23 UTC by maxdlr

- add User controller
- add username to user entity
- add stats number and tabs to user dashboard
- done user dashboard

2023-06-22 06:46 UTC, val-fr69 approved these changes

2023-06-22 06:54 UTC, aldaitzwild requested changes

2023-06-22 06:54 UTC, aldaitzwild commented on src/Controller/VideoController.php
> +        User $user,
This is not aproper way to get a user

2023-06-22 11:46 UTC, l00ma requested changes

2023-06-22 11:46 UTC, l00ma commented on src/Controller/UserController.php
I think (you have to test) there is a better way to do it, without sending user id in url and without calling User $user in your index method (do as you did in src/Controller/VideoController.php).
Then you can use app.user.username instead of user.username in your twig file templates/user/index.html.twig.

Note that you can use app.user.id, app.user.username, app.user.email, app.user.viewLaterVideos and so on directly in twig without calling User in index method.

You'll find a sample in BigThumbnail.html.twig lines 12 to 46

2023-06-22 12:07 UTC, l00ma requested changes

2023-06-22 12:43 UTC, l00ma approved these changes

2023-06-23 06:42 UTC, aldaitzwild approved these changes

2023-06-23 06:43 UTC, merged